"""Rename groups to communities

Revision ID: 18d1777892c2
Revises: c16326a5c253
Create Date: 2026-02-02 13:57:17.089105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d1777892c2'
down_revision = 'c16326a5c253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('communities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('privacy_type', sa.String(length=20), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('icon_image', sa.String(length=255), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('university_restriction', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_communities_created_by_users')),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    op.create_table('community_hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_community_hashtags_community_id_communities')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'community_id', name='uq_community_hashtag_name_community')
    )
    op.create_table('community_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_community_members_community_id_communities')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_community_members_user_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_id', 'user_id', name='unique_community_member')
    )
    op.create_table('community_posts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('community_id', sa.String(), nullable=False),
    sa.Column('yap_id', sa.String(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_community_posts_community_id_communities')),
    sa.ForeignKeyConstraint(['yap_id'], ['yaps.id'], name=op.f('fk_community_posts_yap_id_yaps')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('community_post_hashtags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_post_id', sa.String(), nullable=False),
    sa.Column('community_hashtag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_hashtag_id'], ['community_hashtags.id'], name=op.f('fk_community_post_hashtags_community_hashtag_id_community_hashtags')),
    sa.ForeignKeyConstraint(['community_post_id'], ['community_posts.id'], name=op.f('fk_community_post_hashtags_community_post_id_community_posts')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('community_post_id', 'community_hashtag_id', name='uq_community_post_hashtag')
    )

    with op.batch_alter_table('enhanced_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_enhanced_notifications_group_id_groups', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_enhanced_notifications_community_id_communities'), 'communities', ['community_id'], ['id'])
        batch_op.drop_column('group_id')

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.String(), nullable=True))
        batch_op.drop_constraint('fk_polls_group_id_groups', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_polls_community_id_communities'), 'communities', ['community_id'], ['id'])
        batch_op.drop_column('group_id')

    op.drop_table('group_members')
    op.drop_table('group_posts')
    op.drop_table('groups')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_slug')
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index('ix_yaps_is_deleted')
        batch_op.create_index(batch_op.f('ix_yaps_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yaps_is_deleted'))
        batch_op.create_index('ix_yaps_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.create_index('ix_products_slug', ['slug'], unique=1)

    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_polls_community_id_communities'), type_='foreignkey')
        batch_op.create_foreign_key('fk_polls_group_id_groups', 'groups', ['group_id'], ['id'])
        batch_op.drop_column('community_id')

    with op.batch_alter_table('enhanced_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_enhanced_notifications_community_id_communities'), type_='foreignkey')
        batch_op.create_foreign_key('fk_enhanced_notifications_group_id_groups', 'groups', ['group_id'], ['id'])
        batch_op.drop_column('community_id')

    op.create_table('groups',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('privacy_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('cover_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('icon_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('rules', sa.TEXT(), nullable=True),
    sa.Column('created_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('member_count', sa.INTEGER(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('university_restriction', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='fk_groups_created_by_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_posts',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('group_id', sa.VARCHAR(), nullable=False),
    sa.Column('yap_id', sa.VARCHAR(), nullable=False),
    sa.Column('is_pinned', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_group_posts_group_id_groups'),
    sa.ForeignKeyConstraint(['yap_id'], ['yaps.id'], name='fk_group_posts_yap_id_yaps'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=True),
    sa.Column('joined_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name='fk_group_members_group_id_groups'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_group_members_user_id_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'user_id', name='unique_group_member')
    )
    op.drop_table('community_post_hashtags')
    op.drop_table('community_posts')
    op.drop_table('community_members')
    op.drop_table('community_hashtags')
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))

    op.drop_table('communities')
    # ### end Alembic commands ###
