"""add slug and university_restriction to communities, fix enhanced_notifications FK, add community_id to yaps

Revision ID: 34ff77d753f8
Revises: 20260209201724_5463ea4b
Create Date: 2026-02-13 09:07:23.593077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ff77d753f8'
down_revision = '20260209201724_5463ea4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('badge_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.drop_index('ix_communities_slug')
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    with op.batch_alter_table('community_hashtags', schema=None) as batch_op:
        batch_op.drop_constraint('uq_community_hashtag_name_community', type_='unique')

    with op.batch_alter_table('community_invites', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.VARCHAR(length=12),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('community_post_hashtags', schema=None) as batch_op:
        batch_op.drop_constraint('uq_community_post_hashtag', type_='unique')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('ix_likes_user_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_slug')
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index('ix_replies_user_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_engagement_multiplier')
        batch_op.create_index(batch_op.f('ix_users_engagement_multiplier'), ['engagement_multiplier'], unique=False)

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index('ix_yaps_original_yap_id')
        batch_op.create_index(batch_op.f('ix_yaps_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yaps_is_deleted'))
        batch_op.create_index('ix_yaps_original_yap_id', ['original_yap_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_engagement_multiplier'))
        batch_op.create_index('ix_users_engagement_multiplier', ['engagement_multiplier'], unique=False)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.create_index('ix_replies_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.create_index('ix_products_slug', ['slug'], unique=1)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index('ix_likes_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('community_post_hashtags', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.create_unique_constraint('uq_community_post_hashtag', ['community_post_id', 'community_hashtag_id'])

    with op.batch_alter_table('community_invites', schema=None) as batch_op:
        batch_op.alter_column('token',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=12),
               existing_nullable=False)

    with op.batch_alter_table('community_hashtags', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_community_hashtag_name_community', ['name', 'community_id'])

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.create_index('ix_communities_slug', ['slug'], unique=1)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column('badge_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
