"""Add payment_provider

Revision ID: 3bf4001984c5
Revises: 4901006fe780
Create Date: 2025-12-31 11:55:59.452193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bf4001984c5'
down_revision = '4901006fe780'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badge_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_provider', sa.String(length=20), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_is_active')
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.create_index('ix_products_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('badge_transactions', schema=None) as batch_op:
        batch_op.drop_column('payment_provider')

    # ### end Alembic commands ###
