"""Add community_id to enhanced_notifications

Revision ID: 46feaa6e2425
Revises: 18d1777892c2
Create Date: 2026-02-03 11:36:58.068736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46feaa6e2425'
down_revision = '18d1777892c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index('ix_communities_slug')
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_slug')
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index('ix_yaps_is_deleted')
        batch_op.create_index(batch_op.f('ix_yaps_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yaps_is_deleted'))
        batch_op.create_index('ix_yaps_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.create_index('ix_products_slug', ['slug'], unique=1)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.create_index('ix_communities_slug', ['slug'], unique=1)

    # ### end Alembic commands ###
