"""Optimise for account deletion

Revision ID: 497d083045a8
Revises: e6f1b25185e8
Create Date: 2026-02-04 08:55:50.942585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '497d083045a8'
down_revision = 'e6f1b25185e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index('ix_communities_slug')
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('ix_likes_reply_id')
        batch_op.create_index(batch_op.f('ix_likes_yap_id'), ['yap_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_is_active')
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index('ix_replies_user_id')
        batch_op.create_index(batch_op.f('ix_replies_yap_id'), ['yap_id'], unique=False)

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index('ix_yaps_is_deleted')
        batch_op.create_index(batch_op.f('ix_yaps_community_id'), ['community_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yaps_community_id'))
        batch_op.create_index('ix_yaps_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replies_yap_id'))
        batch_op.create_index('ix_replies_user_id', ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.create_index('ix_products_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_yap_id'))
        batch_op.create_index('ix_likes_reply_id', ['reply_id'], unique=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.create_index('ix_communities_slug', ['slug'], unique=1)

    # ### end Alembic commands ###
