"""Optimise for account deletion

Revision ID: 7bff6c77a7b7
Revises: 497d083045a8
Create Date: 2026-02-04 08:58:00.570161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bff6c77a7b7'
down_revision = '497d083045a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index('ix_communities_slug')
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index('ix_likes_yap_id')
        batch_op.create_index(batch_op.f('ix_likes_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_is_active')
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index('ix_replies_yap_id')
        batch_op.create_index(batch_op.f('ix_replies_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index('ix_yaps_community_id')
        batch_op.create_index(batch_op.f('ix_yaps_original_yap_id'), ['original_yap_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yaps_original_yap_id'))
        batch_op.create_index('ix_yaps_community_id', ['community_id'], unique=False)

    with op.batch_alter_table('replies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_replies_user_id'))
        batch_op.create_index('ix_replies_yap_id', ['yap_id'], unique=False)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.create_index('ix_products_is_active', ['is_active'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_likes_user_id'))
        batch_op.create_index('ix_likes_yap_id', ['yap_id'], unique=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.create_index('ix_communities_slug', ['slug'], unique=1)

    # ### end Alembic commands ###
