"""Add university and faculty fields to Users

Revision ID: c16326a5c253
Revises: fe051ac3666b
Create Date: 2026-02-01 09:09:40.856001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16326a5c253'
down_revision = 'fe051ac3666b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_restriction', sa.String(length=255), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_slug')
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('faculty', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=255), nullable=True))

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index('ix_yaps_is_deleted')
        batch_op.create_index(batch_op.f('ix_yaps_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yaps_is_deleted'))
        batch_op.create_index('ix_yaps_is_deleted', ['is_deleted'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('faculty')
        batch_op.drop_column('university')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.create_index('ix_products_slug', ['slug'], unique=1)

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_column('university_restriction')

    # ### end Alembic commands ###
