"""Add community_id to yaps table

Revision ID: fbcbf424e996
Revises: 46feaa6e2425
Create Date: 2026-02-03 18:03:41.127043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbcbf424e996'
down_revision = '46feaa6e2425'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index('ix_communities_slug')
        batch_op.create_index(batch_op.f('ix_communities_slug'), ['slug'], unique=True)

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_slug')
        batch_op.create_index(batch_op.f('ix_products_is_active'), ['is_active'], unique=False)

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('community_id', sa.String(), nullable=True))
        batch_op.drop_index('ix_yaps_is_deleted')
        batch_op.create_index(batch_op.f('ix_yaps_community_id'), ['community_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_yaps_community_id_communities'), 'communities', ['community_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_yaps_community_id_communities'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_yaps_community_id'))
        batch_op.create_index('ix_yaps_is_deleted', ['is_deleted'], unique=False)
        batch_op.drop_column('community_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_is_active'))
        batch_op.create_index('ix_products_slug', ['slug'], unique=1)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_slug'))
        batch_op.create_index('ix_communities_slug', ['slug'], unique=1)

    # ### end Alembic commands ###
