"""Add soft delete to yaps and MutedUser table

Revision ID: fe051ac3666b
Revises: e2ee_multi_device
Create Date: 2026-01-31 14:44:09.496423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe051ac3666b'
down_revision = 'f9e8d7c6b5a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('muted_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('muter_id', sa.Integer(), nullable=False),
    sa.Column('muted_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('muter_id != muted_id', name='no_self_mute'),
    sa.ForeignKeyConstraint(['muted_id'], ['users.id'], name=op.f('fk_muted_users_muted_id_users')),
    sa.ForeignKeyConstraint(['muter_id'], ['users.id'], name=op.f('fk_muted_users_muter_id_users')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('muter_id', 'muted_id', name='unique_mute')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_status')
        batch_op.create_index(batch_op.f('ix_products_slug'), ['slug'], unique=True)

    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_yaps_is_deleted'), ['is_deleted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yaps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_yaps_is_deleted'))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_slug'))
        batch_op.create_index('ix_products_status', ['status'], unique=False)

    op.drop_table('muted_users')
    # ### end Alembic commands ###
